"""Added image_data field to Map/Waypoint model

Revision ID: 04f77f6d202b
Revises: b733936520a4
Create Date: 2025-02-05 07:45:50.823149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04f77f6d202b'
down_revision = 'b733936520a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('maps', sa.Column('image_data', sa.LargeBinary(), nullable=True))
    op.add_column('waypoints', sa.Column('image_data', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('waypoints', 'image_data')
    op.drop_column('maps', 'image_data')
    # ### end Alembic commands ###
