"""Add city field to waypoint model

Revision ID: 1b0d10ee5e49
Revises: 2b9d2b9e2c44
Create Date: 2025-05-04 14:16:08.863652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b0d10ee5e49'
down_revision = '2b9d2b9e2c44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('waypoints', sa.Column('city', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('waypoints', 'city')
    # ### end Alembic commands ###
