"""Adding cities and coutries fields to waypoint and map model

Revision ID: 2b9d2b9e2c44
Revises: 83a92febcab2
Create Date: 2025-05-04 14:13:50.381609

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2b9d2b9e2c44'
down_revision = '83a92febcab2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('maps', sa.Column('cities', postgresql.ARRAY(sa.String(length=255)), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('maps', 'cities')
    # ### end Alembic commands ###
