"""Added countries field to Map/Waypoint model

Revision ID: 312104046d5b
Revises: 928938b47f71
Create Date: 2025-02-26 07:14:22.482457

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '312104046d5b'
down_revision = '928938b47f71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('maps', sa.Column('countries', postgresql.ARRAY(sa.String(length=255)), nullable=True))
    op.add_column('waypoints', sa.Column('country', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('waypoints', 'country')
    op.drop_column('maps', 'countries')
    # ### end Alembic commands ###
