"""Added price to Map model

Revision ID: 928938b47f71
Revises: 04f77f6d202b
Create Date: 2025-02-23 15:43:05.321867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '928938b47f71'
down_revision = '04f77f6d202b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('maps', sa.Column('price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('maps', 'price')
    # ### end Alembic commands ###
