"""Add rating and duration to waypoint schema

Revision ID: b733936520a4
Revises: bee0b113bf4f
Create Date: 2024-11-15 13:48:36.469609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b733936520a4'
down_revision = 'bee0b113bf4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('waypoints', sa.Column('rating', sa.Float(), nullable=True))
    op.add_column('waypoints', sa.Column('duration', sa.Interval(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('waypoints', 'duration')
    op.drop_column('waypoints', 'rating')
    # ### end Alembic commands ###
